stages:
  - test
  - release
  - docs

unit:
  image: node:8
  stage: test
  script:
    - npm install
    - npm run test
  artifacts:
    paths:
    - coverage
    - report
  only:
  - develop

tag:
  before_script:
    - npm install --frozen-lockfile
  image: node:8
  stage: release
  script:
    - npx semantic-release-gitlab
  artifacts:
    paths:
    - dist
  only:
  - master

publish:
  before_script:
    - npm install --frozen-lockfile
  image: node:8
  stage: release
  script:
    - npm run build-lib
    - npx npm-publish-git-tag
  only:
  - tags

pages:
  image: node:8
  stage: docs
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
    - dist
  only:
  - tags
